In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./df_encoding_test.csv')

In [3]:
week_dummies = pd.get_dummies(df.weekday)
week_dummies.rename(columns={0: 'Monday', 1:'Tuesday', 2:'Wednesday', 3 : 'Thursday', 4 : 'Friday', 5: 'Saturday', 6:'Sunday'}, inplace=True)

In [4]:
df = pd.concat([df, week_dummies], axis='columns')

In [5]:
df.drop(['airline', 'embarked', 'destination', 'Route', 'stops', 'journey_year', 'weekday', 'arrival_period', 'departure_period', 'duration_hours', 'duration_mins', 'additional_info'], axis=1, inplace=True)

In [6]:
df['Arrived_next_day'] = df['Arrived_next_day'].astype(int)

In [7]:
df.sample(10)

,journey_month,journey_day,dep_hour,dep_min,Arrival_hour,Arrival_min,Arrived_next_day,Duration_in_mins,Air Asia,Air India,...,arrival_late night,arrival_morning,arrival_night,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday
513,5,18,2,15,12,35,0,620,0,0,...,0,1,0,0,0,0,0,0,1,0
2512,6,1,10,0,19,0,0,540,0,0,...,0,0,0,0,0,0,0,0,1,0
1897,5,18,8,0,19,15,0,675,0,0,...,0,0,0,0,0,0,0,0,1,0
765,3,9,4,55,21,20,0,985,0,0,...,0,0,1,0,0,0,0,0,1,0
344,4,21,17,15,19,50,0,155,0,0,...,0,0,0,0,0,0,0,0,0,1
1173,3,3,15,5,1,35,1,630,0,0,...,1,0,0,0,0,0,0,0,0,1
269,3,9,7,30,19,15,0,705,0,0,...,0,0,0,0,0,0,0,0,1,0
264,6,21,6,0,8,45,0,165,0,0,...,0,0,0,0,0,0,0,1,0,0
187,6,3,17,30,1,30,1,480,0,0,...,1,0,0,1,0,0,0,0,0,0
2119,5,1,7,35,19,25,0,710,1,0,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
df.to_csv('../decision_tree/dt_encoded_test.csv', index=False)